name: scsilhouette
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  # Python dependencies
  - python=3.9
  - numpy
  - pandas
  - pooch
  - mygene
  - scanpy
  - requests
  - jupyterlab
  - ipykernel
  - matplotlib
  - seaborn
  - sphinx
  - sphinx-rtd-theme
  - sphinx-autodoc-typehints
  - typer
  - myst-parser
  - nextflow
  # R Kernel and R dependencies
  - r-base
  - r-irkernel
  - r-tidyverse
  - r-seurat
  - r-ggplot2
  - r-dplyr
  - r-matrix
  - r-devtools
  # Bash Kernel
  - bash_kernel

  # Additional utilities
  - pip
  - pip:
      - scvi-tools
      - scikit-learn
      - jupyterlab-git
      - jsonpath_ng
      - pdfkit
      - jinja2
      - weasyprint
